### ISSUE TITLE
Is This Issue Still Being Developed / Monitered ?

### ISSUE THREAD

**Issue by Davy49** [evanshultz/neater-bookmarks#108]
It appears while looking @ open issues that the date of most of them are fairly outdated now.

**Comment by ledenis** [comment]
Indeed, the author of this extension has not updated it for more than 7 years. I suggest to use another extension

**Comment by Davy49** [comment]
Do you have any valid suggestions ?
Thanks,
David

**Comment by ledenis** [comment]
I no longer use any extension for bookmarks but [one user](https://github.com/evanshultz/neater-bookmarks/issues/107#issuecomment-1015039420) found [Bookmarkie](https://chrome.google.com/webstore/detail/bookmarkie-bookmarks-in-a/ahlphbdcaacfhkiajebghpngknafklbj) as a good replacement :)

**Comment by Davy49** [comment]
ledenis,
Per your recommendation I thought I'd give the Bookmarkie extension a try, that's the negative part about extensions, when their developers just decide to stop any further development on them. Thanks so much for taking the time to my question, Please Stay Safe.
David
