### ISSUE TITLE
Support @media queries and remove height limit

### ISSUE THREAD

**Issue by mgutt** [evanshultz/neater-bookmarks#66]
I tried to change the CSS depending on the resolution:
<pre>@media (min-width:1200px) { body {
	width: 480px;
	height: 800px;
	max-height: 800px; /* prevent double scrollbars in popup */
}}</pre>

But they are not supported and it seems that it is not possible to raise the height over 600px?!

**Comment by evanshultz** [comment]
The popup maximum height is fixed by Google. This is covered in many places online, including the GitHub page for Neater Bookmarks at https://github.com/evanshultz/neater-bookmarks.

**Comment by mgutt** [comment]
What a pity. Thanks for your answer.
